export default {
  extends: ['@commitlint/config-conventional'],
  // "Initial plan" commit messages are generated by the Copilot coding agent
  // when it starts a new task and are exempt from conventional-commits validation.
  ignores: [(message) => message.startsWith('Initial plan')],
};
